#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Example_WorkingWithAudio.Resource", IsApplication=true)]

namespace Example_WorkingWithAudio
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int custom_theme_background = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_content_create = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_content_save = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_equalizer_white_48dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_keyboard_arrow_left_white_48dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_menu_copy_holo_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_menu_cut_holo_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_menu_paste_holo_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_menu_search_holo_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_mic_white_48dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_zoom_in_white_48dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int not_recording_button = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int record_button = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int recording_button = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080009
			public const int backButton = 2131230729;
			
			// aapt resource value: 0x7f080001
			public const int loadingText = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int menu_charts = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int menu_edit = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int menu_preferences = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int menu_save = 2131230727;
			
			// aapt resource value: 0x7f080002
			public const int myChart1 = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int nav_toolbar = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int recordingButton2 = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int toolbar = 2131230720;
			
			// aapt resource value: 0x7f08000a
			public const int zoomButton = 2131230730;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Charts = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int toolbar = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int nav_menus = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int top_menus = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int top_menus_chart = 2131165186;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
